import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import NavBar from "./NavBar";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { inter } from "./fonts";
import "@/app/theme-config.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.variable}
      >
        <Theme appearance="light" accentColor="violet">
          <NavBar />
          <main className="p-5">{children}</main>          
        </Theme>
      </body>
    </html>
  );
}
